version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: market-data-api
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - HOSTNAME=0.0.0.0
    env_file:
      - .env.local
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - market-data-network

  # Optional: Local Redis for development
  redis:
    image: redis:7-alpine
    container_name: market-data-redis
    ports:
      - "6379:6379"
    environment:
      - REDIS_PASSWORD=your_redis_password_here
    command: redis-server --requirepass your_redis_password_here
    volumes:
      - redis_data:/data
    restart: unless-stopped
    networks:
      - market-data-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 3s
      retries: 3

networks:
  market-data-network:
    driver: bridge

volumes:
  redis_data:
    driver: local

---
# Development compose override
# Use: docker-compose -f docker-compose.yml -f docker-compose.dev.yml up
version: '3.8'

services:
  app-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: market-data-api-dev
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - ENABLE_LOGGING=true
      - LOG_LEVEL=debug
    env_file:
      - .env.local
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    command: npm run dev
    restart: unless-stopped
    networks:
      - market-data-network 